"""Create initial database schema

Revision ID: c1c3c5a1c065
Revises: 
Create Date: 2025-11-15 20:07:23.138608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c3c5a1c065'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('approver', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('voice', 'chat', name='campaigntypeenum'), nullable=False),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('audience_query', sa.JSON(), nullable=True),
    sa.Column('schedule', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_tenant_id'), 'campaigns', ['tenant_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('bedrooms_pref', sa.Integer(), nullable=True),
    sa.Column('neighborhoods', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_tenant_id'), 'events', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='userroleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('campaign_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('reached', sa.Integer(), nullable=False),
    sa.Column('engaged', sa.Integer(), nullable=False),
    sa.Column('qualified', sa.Integer(), nullable=False),
    sa.Column('booked', sa.Integer(), nullable=False),
    sa.Column('revenue_sar', sa.Float(), nullable=False),
    sa.Column('roas', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_metrics_campaign_id'), 'campaign_metrics', ['campaign_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('channel', sa.Enum('voice', 'chat', name='channelenum'), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('ai_or_human', sa.Enum('AI', 'Human', name='aiorhumanenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('recording_url', sa.String(), nullable=True),
    sa.Column('retention_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_table('voice_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'FAILED', name='voicesessionstatus'), nullable=False),
    sa.Column('simulation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('extracted_intent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_sessions_conversation_id'), 'voice_sessions', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_voice_sessions_tenant_id'), 'voice_sessions', ['tenant_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('property_code', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'canceled', 'completed', name='bookingstatusenum'), nullable=False),
    sa.Column('price_sar', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('voice', 'chat', name='channelenum'), nullable=False),
    sa.Column('created_by', sa.Enum('AI', 'Human', name='aiorhumanenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('preferred_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['voice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_tenant_id'), 'bookings', ['tenant_id'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='calldirectionenum'), nullable=False),
    sa.Column('status', sa.Enum('connected', 'no_answer', 'abandoned', name='callstatusenum'), nullable=False),
    sa.Column('handle_sec', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Enum('qualified', 'booked', 'ticket', 'info', name='calloutcomeenum'), nullable=True),
    sa.Column('ai_or_human', sa.Enum('AI', 'Human', name='aiorhumanenum'), nullable=False),
    sa.Column('recording_url', sa.String(), nullable=True),
    sa.Column('retention_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_conversation_id'), 'calls', ['conversation_id'], unique=False)
    op.create_table('handoffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('from_tier', sa.String(), nullable=False),
    sa.Column('to_tier', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'med', 'high', 'urgent', name='ticketpriorityenum'), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'pending_approval', 'resolved', name='ticketstatusenum'), nullable=False),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('issue', sa.Text(), nullable=True),
    sa.Column('project', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['voice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_tenant_id'), 'tickets', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_tenant_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('handoffs')
    op.drop_index(op.f('ix_calls_conversation_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_bookings_tenant_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_voice_sessions_tenant_id'), table_name='voice_sessions')
    op.drop_index(op.f('ix_voice_sessions_conversation_id'), table_name='voice_sessions')
    op.drop_table('voice_sessions')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_campaign_metrics_campaign_id'), table_name='campaign_metrics')
    op.drop_table('campaign_metrics')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_events_tenant_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_campaigns_tenant_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_table('approvals')
    # ### end Alembic commands ###
