"""Add bulk calling feature

Revision ID: d5949b6ea945
Revises: 0caf10b8fb29
Create Date: 2026-01-17 21:36:42.989665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5949b6ea945'
down_revision: Union[str, None] = '0caf10b8fb29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_call_scripts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_call_scripts_tenant_id'), 'bulk_call_scripts', ['tenant_id'], unique=False)
    op.create_table('bulk_call_campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'paused', 'completed', 'failed', 'cancelled', name='bulkcallstatusenum'), nullable=False),
    sa.Column('customer_ids', sa.JSON(), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('completed_calls', sa.Integer(), nullable=False),
    sa.Column('failed_calls', sa.Integer(), nullable=False),
    sa.Column('successful_calls', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.String(), nullable=True),
    sa.Column('script_content', sa.Text(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('concurrency_limit', sa.Integer(), nullable=False),
    sa.Column('use_knowledge_base', sa.Boolean(), nullable=False),
    sa.Column('custom_system_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['bulk_call_scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_call_campaigns_tenant_id'), 'bulk_call_campaigns', ['tenant_id'], unique=False)
    op.create_table('bulk_call_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('call_id', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'in_progress', 'success', 'failed', 'voicemail', 'no_answer', 'busy', 'cancelled', name='bulkcallresultstatusenum'), nullable=False),
    sa.Column('outcome', sa.Enum('interested', 'not_interested', 'follow_up_requested', 'appointment_booked', 'information_only', 'wrong_number', 'do_not_call', name='bulkcalloutcomeenum'), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('recording_url', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('twilio_call_sid', sa.String(), nullable=True),
    sa.Column('twilio_status', sa.String(), nullable=True),
    sa.Column('voice_session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['bulk_call_campaigns.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['voice_session_id'], ['voice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_call_results_tenant_id'), 'bulk_call_results', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bulk_call_results_tenant_id'), table_name='bulk_call_results')
    op.drop_table('bulk_call_results')
    op.drop_index(op.f('ix_bulk_call_campaigns_tenant_id'), table_name='bulk_call_campaigns')
    op.drop_table('bulk_call_campaigns')
    op.drop_index(op.f('ix_bulk_call_scripts_tenant_id'), table_name='bulk_call_scripts')
    op.drop_table('bulk_call_scripts')
    # ### end Alembic commands ###
